spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    password: 123
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp